<?php
   /* Some smart comment */
   return array(
       'active_widgets_explanation'=>'Trenutno aktivni widgets:', // Active widgets explanation
       'add_category_button'=>'Dodaj Kategorija', // Add category
       'add_field_button'=>'Dodaj polje', // Add field
       'add_link_button'=>'Dodaj povezavo', // Add link button
       'add_link_link'=>'- ^ 1add povezava ^ 2', // - ^1add link^2
       'add_new_field'=>'Dodaj novo polje', // Add_new_field
       'add_new_title'=>'Dodaj nov naslov', // Add new title
       'add_page_button'=>'Dodaj stran', // Add page
       'add_title_button'=>'Dodaj Naslov', // Add title
       'add_widget_button'=>'Dodaj Widget', // Add_widget
       'add_widget_link'=>'- ^ 1add widget ^ 2', // - ^1add widget^2
       'admin_title'=>'Uprava center', // Admin title
       'after_footer'=>'Po povezave v nogi', // After footer
       'after_main_menu'=>'Po zavihki na vrhu', // After main menu
       'after_x'=>'Po "^"', //After "^"
       'after_x_tab'=>'Po "^" zanka', //After "^" tab
       'approve_user_popup'=>'Odobri uporabniku', // approve user popup
       'approve_users_title'=>'Odobri uporabnikom', // approve users title
       'basic_editor'=>'Urejevalnik Basic', 
       'before_main_menu'=>'Pred zavihki na vrhu', 
       'blobs_directory_error'=>'Imenik ^ opredeljena kot QA_BLOBS_DIRECTORY ne more pisati na spletni strežnik.', //The directory ^ defined as QA_BLOBS_DIRECTORY is not writable by the web server.
       'blobs_move_complete'=>'Migracije naloženih slik in dokumentov končana.', 
       'blobs_move_moved'=>'Migracije ^ 1 ^ 2 naložili slik in dokumentov', //Migration ^1 of ^2 uploaded images and documents
       'blobs_stop'=>'Stop selijo', 
       'blobs_to_db'=>'Blobs do podatkovne zbirke', 
       'blobs_to_db_note'=>'- Selitev vse slike in dokumente iz diska datoteke s podatkovno zbirko', 
       'blobs_to_disk'=>'Blobs na disk', 
       'blobs_to_disk_note'=>'- Selitev vse slike in dokumentov iz baze podatkov na disk datotek', 
       'block_button'=>'blok', 
       'block_ips_note'=>'Uporabite vezaj za razpone, ali *, da se ujemajo vsako številko. Primeri: 192.168.0.4, 192.168.0.0-192.168.0.31, 192.168.0 *.', 
       'block_user_popup'=>'Blokiraj uporabnika', 
       'block_words_note'=>'Uporabite * se ujema nobenega pisma. Primeri: doh (se ujema samo točno besedno DOH), doh * (bo ujemalo doh ali dohno), naredite * h (se bo ujemalo DOH, dooh, testo).', 
       'cancel_mailing_button'=>'Prekliči poštni', 
       'categories'=>'Kategorije', 
       'categories_introduction'=>'Če želite začeti s kategorijami, kliknite "Dodaj kategorijo" gumb.', 
       'categories_not_shown'=>'Nekatera vprašanja so kategorije, ki se ne bodo prikazani.', 
       'categories_title'=>'Kategorije', 
       'category_add_sub'=>'dodaj podkategorijo', 
       'category_added'=>'Kategorija dodane', 
       'category_already_used'=>'To se ga kategoriji že uporablja', 
       'category_default_slug'=>'category- ^', //category-^
       'category_description'=>'Neobvezno opis kategorije:', 
       'category_max_depth_x'=>'Nekaj ​​možnosti je mogoče skriti, da se prepreči kategorijo gredo globlje od ^ ravni.', //Some options may be hidden to prevent a category going deeper than ^ levels.
       'category_move_parent'=>'premik k drugačni od staršev', 
       'category_name'=>'Ime kategorije:', 
       'category_name_first'=>'Ime prve kategorije:', 
       'category_no_add_subs_x'=>'Ta kategorija podkategorije, ne more imeti, ker je že ^ Ravni dol.', //This category cannot have sub-categories because it is already ^ levels down.
       'category_no_delete_subs'=>'Ta kategorija ni mogoče izbrisati, ker ima pod-kategorijo.', 
       'category_no_sub_error'=>'^ Q vprašanje / ov v tej kategoriji nima podkategorije - ^ 1set podkategorija ^ 2', //^q question/s in this category have no sub-category - ^1set sub-category^2
       'category_no_sub_to'=>'Premaknete na vprašanja v ^ brez podkategorija:', //Move questions in ^ with no sub-category to:
       'category_no_subs'=>'Noben', 
       'category_none_error'=>'^ Q vprašanje / s trenutno nimajo kategorijo - ^ kategorija 1set ^ 2', //^q question/s currently have no category - ^1set category^2
       'category_none_to'=>'Premakniti vprašanj brez kategorijo:', 
       'category_parent'=>'Nadrejena kategorija:', 
       'category_saved'=>'Kategorija shranjena', 
       'category_slug'=>'Kategorija slug - URL fragment:', 
       'category_subs'=>'Podkategoriji:', 
       'category_top_level'=>'Noben od staršev (na najvišji ravni)', 
       'characters'=>'znaki', 
       'check_language_suffix'=>'- ^ 1check jezikovne datoteke ^ 2', // - ^1check language files^2
       'click_name_edit'=>'Custom strani ali povezave:', 
       'database_cleanup'=>'Baze podatkov čistilne akcije', 
       'delete_category'=>'Izbrisati to kategorijo', 
       'delete_category_reassign'=>'Izbrisati to kategorijo in dodelite svoje vprašanja:', 
       'delete_field'=>'Izbrisati to polje', 
       'delete_hidden'=>'Brisanje skritih sporočil', 
       'delete_hidden_complete'=>'Vse skritih sporočil brez vzdrževanih so bile izbrisane', 
       'delete_hidden_note'=>'- Vse skrite vprašanja, odgovori in komentarji brez vzdrževanih družinskih članov', 
       'delete_link'=>'Izbriši to povezavo', 
       'delete_page'=>'Izbriši stran', 
       'delete_stop'=>'Stop brisanje', 
       'delete_title'=>'Izbriši ta naslov', 
       'delete_widget_position'=>'Izbriši ta widget iz tega položaja', 
       'edit_custom_page'=>'Uredite stran po meri', 
       'edit_field'=>'- ^ 1edit polje ^ 2', // - ^1edit field^2
       'edit_link'=>'- ^ 1edit povezava ^ 2', // - ^1edit link^2
       'edit_page'=>'- ^ 1edit stran ^ 2', // - ^1edit page^2
       'edit_title'=>'- ^ Naslov 1edit ^ 2', // - ^1edit title^2
       'emails_per_minute'=>'e-pošto na minuto', 
       'emails_title'=>'E-pošta', 
       'feed_link'=>'Feed', 
       'feed_link_example'=>'Primer feed', 
       'feeds_title'=>'RSS', 
       'field_link_url'=>'Povezana URL', 
       'field_multi_line'=>'Več vrstic besedila', 
       'field_name'=>'Ime polja:', 
       'field_single_line'=>'Enotni vrstica besedila', 
       'field_type'=>'Vrsta vsebine:', 
       'first'=>'Prva', 
       'flagged_title'=>'Zastavico', 
       'form_security_expired'=>'Varnostna oblika koda je potekel - poskusite znova', 
       'from_anon'=>'Iz anonimnih:', 
       'from_users'=>'Uporabnikov:', 
       'general_title'=>'Splošno', 
       'hidden_answers_deleted'=>'Črta ^ 1 od ^ 2 skritih odgovorov brez vzdrževanih ...', //Deleted ^1 of ^2 hidden answers without dependents...
       'hidden_comments_deleted'=>'Črta ^ 1 od ^ 2 skrite komentarje ...', //Deleted ^1 of ^2 hidden comments...
       'hidden_questions_deleted'=>'Črta ^ 1 od ^ 2 skritih vprašanj brez vzdrževanih ...', //Deleted ^1 of ^2 hidden questions without dependents...
       'hidden_title'=>'Skrita', 
       'hotness_factors'=>'Relativni pomen za vprašanje priljubljenosti:', 
       'ip_address_pages'=>'IP naslov strani', 
       'layout_title'=>'Postavitev', 
       'link_name'=>'Besedilo povezave:', 
       'link_new_window'=>'Odpri v novem oknu', 
       'link_url'=>'URL povezavo - absolutna ali relativna Q2A koren:', 
       'lists_title'=>'Seznami', 
       'mailing_complete'=>'Poštni je končana', 
       'mailing_explanation'=>'Uporabniki bodo lahko odjavite na njihovi strani računa.', 
       'mailing_progress'=>'Poštni izpolniti za ^ 1 od ^ 2 uporabnikov ...', //Mailing completed for ^1 of ^2 users...
       'mailing_title'=>'Mailing', 
       'mailing_unsubscribe'=>'Odjavi povezava bo dodana na dnu vsakega sporočila.', 
       'maintenance_admin_only'=>'Vaša spletna stran je v ^ 1Vzdrževanje ^ 2 in je trenutno nedostopna rednih uporabnikov.', //Your site is in ^1maintenance^2 and is currently inaccessible to regular users.
       'maximum_x'=>'(Max ^)', // (max ^)
       'moderate_title'=>'Zmerna', 
       'module_x_database_init'=>'^ 1 ^ 2 modula zahteva nekaj ^ 3database inicializacija ^ 4.', //The ^1 ^2 module requires some ^3database initialization^4.
       'most_flagged_title'=>'Označena vsebina', 
       'mysql_version'=>'MySQL verzija:', 
       'nav_links_explanation'=>'Prikaži navigacijske povezave:', 
       'nav_qa_is_home'=>'Q & A (povezave na spletno stran)', 
       'neat_urls_note'=>'(Zahteva ^ 1htaccess ^ 2 datoteke)', // (requires ^1htaccess ^2 file)
       'no_approve_found'=>'Ni vsebine čaka na odobritev', 
       'no_classification'=>'Noben', 
       'no_flagged_found'=>'Ne označeni ugotovljena vsebnost', 
       'no_hidden_found'=>'Ne skrito vsebino najti', 
       'no_image_gd'=>'Nameščena različica PHP je bil preveden brez podpore GD slike, tako da uporabniki ne morejo neposredno naložite svoje avatarje.', //The installed version of PHP was compiled without support for GD image so that users can not directly upload their avatars.
       'no_link'=>'Ni povezave', // No link
       'no_multibyte'=>'Nameščena različica PHP je bil preveden brez podpore večbajtne niza. Iskanje bo manj učinkovita za non-latinici.', //The installed version of PHP was compiled without support multibyte string. The search will be less effective for non-Latin characters.
       'no_privileges'=>'Samo administratorji lahko dostopajo do te strani.', //Only administrators can access this page.
       'no_unapproved_found'=>'Ni uporabnikov, ki čakajo na odobritev', //There are no users waiting for approval
       'not_logged_in'=>'Prosimo, ^ 1log v ^ 2 kot skrbnik za dostop do te strani.', //Please ^ 1log in ^ 2 as the administrator to access this page.
       'opposite_main_menu'=>'Far konec zavihki na vrhu', //Far end of the tabs at the top
       'options'=>'Možnosti', //Option
       'options_reset'=>'Ponastaviti možnosti', //Options reset
       'options_saved'=>'Možnosti shranjene', //Options saved
       'page_already_used'=>'To se s strani že uporablja', //Page already used
       'page_content_html'=>'Vsebina prikazati na stran - HTML dovoljeno:', //The content displayed on the site - HTML allowed:
       'page_default_slug'=>'celostransko objavo ^', //page ^
       'page_heading'=>'Postavka se prikaže na vrhu strani:', //This item appears at the top of the page:
       'page_name'=>'Ime strani (uporabljajo tudi za kartici ali povezave):', //Name page (used for card or links):
       'page_slug'=>'Slug stran (URL fragment):', //Slug page (URL fragment):
       'pages_explanation'=>'Kliknite na "Dodaj stran" gumb, da dodate vsebino po meri za vaše Q2A mestu, ali "Add Link" povezati s katero koli drugo spletno stran.', //Click on the "Add Page" button to add custom content to your site Q2A or "Add Link" link to any other website.
       'pages_title'=>'Strani', //Pages title
       'pause_mailing_button'=>'Pause Mailing', //Pause Mailing
       'per_ip_hour'=>'na IP / uro', //on IP / hour
       'per_user_hour'=>'na uporabnika / uro', //per user / hour
       'permissions_title'=>'Dovoljenja', //Permissions
       'permit_to_view'=>'Vidno:', //Permit to view
       'php_version'=>'PHP verzija:', //PHP version
       'pixels'=>'slikovnih pik', //pixels
       'plugin_module'=>'(Plugin modul: ^)', // (Plugin module: ^)
       'plugin_pages_explanation'=>'Strani so na voljo preko vtičnikov:', //Pages are available through plug-ins:
       'plugins_title'=>'Plugins', //Plugins
       'points'=>'točke', //points
       'points_defaults_shown'=>'Privzeta vrednost je prikazano spodaj, vendar še ne uporablja:', The default value is shown below, but does not apply to:
       'points_required'=>'Točke se zahteva za sprejem naslov:', //Points required for admission the following address:
       'points_title'=>'Točke', //Points
       'position'=>'Položaj:', //Position:
       'posting_title'=>Napotitev'', //Posting title
       'profile_fields'=>'Dodatna polja na uporabniških straneh ali prijavnico:', //Additional fields on user pages or registration:
       'q2a_build_date'=>'Build datum:', //Build date:
       'q2a_db_size'=>'Velikost baze podatkov:', //The size of the database:
       'q2a_db_version'=>'Q2A različica zbirke podatkov:', //Q2A version of the database:
       'q2a_latest_version'=>'Najnovejša različica:', //The latest version:
       'q2a_version'=>'Question2Answer različica:', //Question2Answer različica:
       'question_lists'=>'Seznami vprašanje', //Questions lists
       'question_pages'=>'Vprašanje strani', //Question pages
       'recalc_categories'=>'Preračunati kategorije', //Recalculate categories
       'recalc_categories_backpaths'=>'Preračunavanjem URL poti za ^ 1 od ^ 2 kategorijah ...', //Recalculating URL paths for ^ 1 of ^ 2 categories ...
       'recalc_categories_complete'=>'Vse kategorije bilo uspešno preračunali.', //All categories have been successfully recalculated.
       'recalc_categories_note'=>'- Za poštne kategorije in kategorije grofov', //- Postal category and category Counts
       'recalc_categories_recounting'=>'Pripoveduje vprašanja za ^ 1 od ^ 2 kategorijah ...', //Recounting questions for ^ 1 of ^ 2 categories ...
       'recalc_categories_updated'=>'Preračunane za ^ 1 od ^ 2 delovnih mest ...', //Recalculated for ^ 1 of ^ 2 posts ...
       'recalc_points'=>'Preračunati uporabniških točk', //Recalculated User points
       'recalc_points_complete'=>'Vse uporabniške točke so bile uspešno preračunali.', //All user points were successfully recalculatedd.
       'recalc_points_note'=>'- Za razvrstitev uporabnikov in točk zaslonov', //- For a breakdown of points and screens
       'recalc_points_recalced'=>'Preračunane za ^ 1 od ^ 2 uporabnikov ...', //Recalculated for ^ 1 of ^ 2 users ...
       'recalc_points_usercount'=>'Ocenjevanje skupno število uporabnikov, ...', //Evaluation of the total number of users, ...
       'recalc_posts_count'=>'Dobili skupno število vprašanj, odgovore in komentarje ...', //Get the total number of questions, answers, and comments ...
       'recalc_stop'=>'Stop preračunu', //Stop conversion
       'recent_approve_title'=>'Nedavna čakanja za odobritev vsebine', //Recent waiting for the approval of contents
       'recent_hidden_title'=>'Nedavna skrito vsebino', //Recent hidden content
       'recount_posts'=>'Pripovedujejo objav', //Recounted posts
       'recount_posts_as_recounted'=>'Pripovedoval odgovori in hotness za ^ 1 od ^ 2 delovnih mest ...', //Recounted answers and hotness for ^ 1 of ^ 2 posts ...
       'recount_posts_complete'=>'Vsa delovna mesta so bile uspešno pripovedoval.', //All posts have been successfully recounted.
       'recount_posts_note'=>'- Število odgovorov, glasov, zastave in hotness za vsako delovno mesto', //- Number of responses votes, pledges and hotness for each job
       'recount_posts_stop'=>'Stop pripoveduje', //Stop recounting posts
       'recount_posts_votes_recounted'=>'Pripovedoval glasov in zastave za ^ 1 od ^ 2 delovnih mest ...', //Recounted votes and flags for ^ 1 of ^ 2 posts ...
       'refill_events'=>'Napolnim tokove dogodkov', //Refill currents events
       'refill_events_complete'=>'Vsi dogodki potoki so se uspešno ponovno napolniti', //All events streams were successfully completed
       'refill_events_note'=>'- Za seznam posameznih uporabnikov o novostih', //- For a list of individual users of updates
       'refill_events_refilled'=>'Ponovno napolni za ^ 1 od ^ 2 vprašanja ...', //Refilled for ^ 1 of ^ 2 questions ...
       'registration_fields'=>'dodamo polja registraciji', //add registration fields 
       'reindex_content'=>'Indeksiraj vsebina', //Reindex content
       'reindex_content_note'=>'- Za iskanje in s tem povezanih vprašanj predlogi', //- To search for and related issues proposals
       'reindex_content_stop'=>'Stop indeksiranje', //Stop indexing
       'reindex_pages_reindexed'=>'Reindexed ^ 1 ^ 2 straneh ...', //Reindexed ^ 1 of ^ 2 pages ...
       'reindex_posts_complete'=>'Vsa delovna mesta so bile uspešno reindexed.', //All posts have been successfully reindexed.
       'reindex_posts_reindexed'=>'Reindexed ^ 1 ^ 2 delovnih mest ...', //Reindexed ^ 1 of ^ 2 posts ...
       'reindex_posts_wordcounted'=>'Pripovedoval ^ 1 ^ 2 besed ...', //Recounted ^ 1 of ^ 2 words ...
       'requires_php_version'=>'Onemogočeno - zahteva PHP ^ ali pozneje', //Disabled - requires PHP ^ or later
       'requires_q2a_version'=>'Onemogočeno - zahteva Question2Answer ^ ali pozneje', //Disabled - requires Question2Answer ^ or later
       'reset_options_button'=>'Ponastavi na privzete nastavitve', //Set the default settings
       'reset_options_confirm'=>'Ali ste prepričani, da želite ponastaviti vse možnosti na tej strani na njihove privzete vrednosti?', //Are you sure you want to set all the options on this page to their default values?
       'resume_mailing_button'=>'Nadaljuj Mailing', //Resume mailing
       'save_options_button'=>'Možnosti shranjevanja', //Save options
       'save_recalc_button'=>'Shranite in ponovno', //Save and reuse
       'save_view_button'=>'Prihranite in View', //Save and View
       'send_test_button'=>'Pošlji test to Me', //Send a test to Me
       'show_defaults_button'=>'Prikaži Defaults', //Show Defaults
       'show_on_register_form'=>'Prikaži polje na obrazec za registracijo uporabnika', //Show box on the registration form user
       'slug_bad_chars'=>'Slug ne sme vsebovati teh znakov: ^', //The slug may not contain these characters: ^
       'slug_reserved'=>'Ta slug je rezervirano za uporabo z drugo stran', //This slug is reserved for use by the other side
       'spam_title'=>'Spam', //Spam
       'start_mailing_button'=>'Začnite poštni', //Start mailing
       'stats_title'=>'Statistika', //Statistics
       'stop_recalc_warning'=>'Podatkovna baza čist-up operacija poteka. Če zaprete to stran zdaj, bo postopek prekinjen.', //The database clean-up operation is conducted. If you close this page now, the process is interrupted.
       'tag_pages'=>'Tag strani', //Tag pages
       'tags'=>'Tags', //Tags
       'tags_and_categories'=>'Oznake in kategorije', //Tags and categories
       'tags_not_shown'=>'Nekatera vprašanja so oznake, ki jih ne bodo prikazani.', //Some of the questions are tags that you will not be displayed.
       'test_sent_to_x'=>'Test sporočilo je bilo poslano ^', //The test message was sent to ^
       'title_already_used'=>'Ta vrednost se še drug naziv že uporablja', //This value is another title is already in use
       'top_level_categories'=>'Kategorije na najvišji ravni:', //Top level categories
       'total_as'=>'Skupaj odgovorov:', //Total of answers:
       'total_cs'=>'Skupaj komentarjev:', //Total comments:
       'total_qs'=>'Skupaj vprašanja:', //Total questions:
       'unnamed_plugin'=>'Neimenovani Plugin', //Unnamed plugin
       'upgrade_db'=>'Vaš Question2Answer baza podatkov mora biti ^ 1upgraded ^ 2 za to različico.', //Your Question2Answer database needs to be ^ 1upgraded ^ 2 for this version.
       'url_format_note'=>'Možnosti z oznako ^ delajo za konfiguracijo vašega spletnega mesta. Za najboljšo Search Engine Optimization (SEO), uporabite prvo ^ možnost na voljo.', //Options with the ^ label are working for your site's configuration. For best search engine optimization (SEO), use the first ^ option available.
       'user_pages'=>'Uporabniške strani', //User pages
       'user_title'=>'Uporabnik title - HTML dovoljeno:', //User title - HTML allowed:
       'user_titles'=>'Uporabniške naslovov, ki temeljijo na točkah:', //User addresses, based on the points:
       'users_active'=>'Aktivni uporabniki:', //Active users:
       'users_must_have'=>'Uporabniki morajo imeti', //Users must have
       'users_posted'=>'Uporabniki, ki so napoteni:', //Users who posted:
       'users_registered'=>'Registrirani uporabniki:', //Registered users:
       'users_title'=>'Uporabniki', //Users 
       'users_voted'=>'Uporabniki, ki so glasovali:', //Users voted
       'version_get_x'=>'dobili ^', //get ^
       'version_latest'=>'Zadnji', //Latest
       'version_latest_unknown'=>'Zadnji neznano', //latest unknown
       'version_requires_php'=>'^ 1 zahteva, da PHP ^ 2', //^ 1 requires PHP ^ 2
       'version_requires_q2a'=>'^ 1 zahteva Q2A ^ 2', //^ 1 requires Q2A ^ 2
       'viewing_title'=>'Pregled', //Review
       'widget_all_pages'=>'Prikaži widget v tem položaju na vseh razpoložljivih strani', //View the widget in this position on all available pages
       'widget_global_options'=>'- ^ 1options ^ 2', // - ^ 1options ^ 2
       'widget_name'=>'Ime gradnika:', //Widget name:
       'widget_no_positions'=>'Ta widget je že dodana vsaki je na voljo položaj.', //This widget is already added to each available position.
       'widget_not_available'=>'Ta pripomoček ni na voljo. To bi lahko bilo, ker je plugin zagotavlja widget ni več nameščen.', //This utility is not available. This could be because the plugin provides a widget is no longer installed.
       'widget_pages_explanation'=>'Prikaži gradnik v tem položaju na naslednjih straneh:', //View the widget in this post on the following pages:
       'widgets_explanation'=>'Na voljo widgets:', //Available widgets:
   );
